// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVae3AtLRJSVy9Tsm36eXq9l9nP5_cDdg',
    appId: '1:645036786953:web:9ef68aee099ef426ff7fd8',
    messagingSenderId: '645036786953',
    projectId: 'daylog-ssafy',
    authDomain: 'daylog-ssafy.firebaseapp.com',
    storageBucket: 'daylog-ssafy.appspot.com',
    measurementId: 'G-J694E88GXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrMo0QfLiTFpGMZWx4tjB0xcJEyblg63Y',
    appId: '1:645036786953:android:9eca3750dac370d0ff7fd8',
    messagingSenderId: '645036786953',
    projectId: 'daylog-ssafy',
    storageBucket: 'daylog-ssafy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzYVNeKyZJYXTFpPu9bco_OGMErMoplQ',
    appId: '1:645036786953:ios:f97634f1fd6dce49ff7fd8',
    messagingSenderId: '645036786953',
    projectId: 'daylog-ssafy',
    storageBucket: 'daylog-ssafy.appspot.com',
    iosBundleId: 'com.example.openviduflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzYVNeKyZJYXTFpPu9bco_OGMErMoplQ',
    appId: '1:645036786953:ios:f97634f1fd6dce49ff7fd8',
    messagingSenderId: '645036786953',
    projectId: 'daylog-ssafy',
    storageBucket: 'daylog-ssafy.appspot.com',
    iosBundleId: 'com.example.openviduflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVae3AtLRJSVy9Tsm36eXq9l9nP5_cDdg',
    appId: '1:645036786953:web:643bf4404cb1b3ccff7fd8',
    messagingSenderId: '645036786953',
    projectId: 'daylog-ssafy',
    authDomain: 'daylog-ssafy.firebaseapp.com',
    storageBucket: 'daylog-ssafy.appspot.com',
    measurementId: 'G-LFHXJQSBD6',
  );
}
